version: '3.1'

services:
  notes_telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      BOT_TOKEN: paste_your_bot_token_from_BotFather
      BOT_NICKNAME: your_bot_nick
      ADMIN_TELEGRAM_ID: 44444444
      DB_URL: jdbc:postgresql://localhost:5432/telegram
      DB_USER: telegram_user
      DB_PASSWORD: telegram_user_password
